### ISSUE TITLE
Implement JK algorithms

### ISSUE THREAD

**Issue by rdcunha** [MolSSI-SSS/QM_2017_SSS_Team11#28]

**Comment by rdcunha** [comment]
JK algorithm implemented and fixed up. Build passing.

**Comment by bgpeyton** [comment]
Fix hard-coded basis in aux basis function (line ~12 or so)

**Comment by dgasmith** [comment]
BTW, no need for transpose [here](https://github.com/MolSSI-SSS/QM_2017_SSS_Team11/blob/master/scf_11/jk.py#L42). This,

```python
xi1 = np.einsum("qms,ps->qmp", Pls, Cocc.T)
```
is equivalent to,

```python
xi1 = np.einsum("qms,sp->qmp", Pls, Cocc)
```

**Comment by bgpeyton** [comment]
Hard-coded basis and unneeded transpose fixed.
